# Generated by Django 6.0.3 on 2026-03-30 20:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historialsolicitud',
            name='estado_anterior',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='solicitudes.estadosolicitud', verbose_name='Estado anterior'),
        ),
    ]
