# Generated by Django 6.0.3 on 2026-03-11 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_usuario_esta_activo_alter_usuario_persona'),
    ]

    operations = [
    ]
