# Generated by Django 6.0.3 on 2026-04-20 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_usuario_first_name_remove_usuario_last_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(db_index=True, max_length=150, verbose_name='Nombre de usuario')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Dirección IP')),
                ('user_agent', models.TextField(blank=True, null=True, verbose_name='User Agent')),
                ('success', models.BooleanField(default=False, verbose_name='¿Exitoso?')),
                ('attempt_time', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y hora del intento')),
            ],
            options={
                'verbose_name': 'Intento de Login',
                'verbose_name_plural': 'Intentos de Login',
                'ordering': ['-attempt_time'],
                'indexes': [models.Index(fields=['username', 'attempt_time'], name='users_login_usernam_976d10_idx'), models.Index(fields=['ip_address', 'attempt_time'], name='users_login_ip_addr_812c26_idx')],
            },
        ),
    ]
