# Generated by Django 6.0.3 on 2026-03-14 02:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('almacenes', '0001_initial'),
        ('productos', '0001_initial'),
        ('proveedores', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingreso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_eliminacion', models.DateTimeField(blank=True, null=True)),
                ('accion', models.JSONField(blank=True, null=True)),
                ('codigo', models.CharField(max_length=50, unique=True, verbose_name='Código')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('comprobante', models.CharField(max_length=100, verbose_name='N° Comprobante')),
                ('fecha_ingreso', models.DateTimeField(verbose_name='Fecha de ingreso')),
                ('gestion', models.IntegerField(verbose_name='Gestión')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('COMPLETADO', 'Completado'), ('ANULADO', 'Anulado')], default='PENDIENTE', max_length=20, verbose_name='Estado')),
                ('almacen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ingresos', to='almacenes.almacen', verbose_name='Almacén')),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('eliminado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('modificado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ingresos', to='proveedores.proveedor', verbose_name='Proveedor')),
                ('subalmacen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ingresos', to='almacenes.subalmacen', verbose_name='Subalmacén')),
            ],
            options={
                'verbose_name': 'Ingreso',
                'verbose_name_plural': 'Ingresos',
                'ordering': ['-fecha_ingreso'],
            },
        ),
        migrations.CreateModel(
            name='IngresoDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Cantidad')),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio Unitario')),
                ('ingreso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='ingresos.ingreso')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='productos.producto', verbose_name='Producto')),
            ],
            options={
                'verbose_name': 'Detalle de Ingreso',
                'verbose_name_plural': 'Detalles de Ingreso',
            },
        ),
    ]
