# Generated by Django 6.0.3 on 2026-03-18 19:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almacenes', '0001_initial'),
        ('ingresos', '0001_initial'),
        ('productos', '0001_initial'),
        ('proveedores', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoIngreso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True, verbose_name='Nombre del estado')),
                ('codigo', models.CharField(max_length=20, unique=True, verbose_name='Código')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('orden', models.IntegerField(default=0, verbose_name='Orden')),
            ],
            options={
                'verbose_name': 'Estado de Ingreso',
                'verbose_name_plural': 'Estados de Ingreso',
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.AddField(
            model_name='ingreso',
            name='fecha_anulacion',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de anulación'),
        ),
        migrations.AddField(
            model_name='ingreso',
            name='observacion_anulacion',
            field=models.TextField(blank=True, null=True, verbose_name='Observación de anulación'),
        ),
        migrations.AddField(
            model_name='ingresodetalle',
            name='fecha_actualizacion_stock',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha actualización stock'),
        ),
        migrations.AddField(
            model_name='ingresodetalle',
            name='stock_actualizado',
            field=models.BooleanField(default=False, verbose_name='Stock actualizado'),
        ),
        migrations.AlterField(
            model_name='ingresodetalle',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ingresos_detalle', to='productos.producto', verbose_name='Producto'),
        ),
        migrations.AddIndex(
            model_name='ingresodetalle',
            index=models.Index(fields=['ingreso', 'producto'], name='ingresos_in_ingreso_edf0c6_idx'),
        ),
        migrations.AlterField(
            model_name='ingreso',
            name='estado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ingresos', to='ingresos.estadoingreso', verbose_name='Estado'),
        ),
        migrations.AddIndex(
            model_name='ingreso',
            index=models.Index(fields=['codigo'], name='ingresos_in_codigo_a5e42c_idx'),
        ),
        migrations.AddIndex(
            model_name='ingreso',
            index=models.Index(fields=['gestion', 'estado'], name='ingresos_in_gestion_110c26_idx'),
        ),
    ]
