# Generated by Django 6.0.3 on 2026-03-14 02:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utilitario', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Feriado',
        ),
    ]
