# Generated by Django 6.0.3 on 2026-03-20 17:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almacenes', '0001_initial'),
        ('ingresos', '0002_estadoingreso_ingreso_fecha_anulacion_and_more'),
        ('productos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MovimientoStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(blank=True, max_length=10, null=True, verbose_name='Tipo')),
                ('cantidad', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Cantidad')),
                ('stock_anterior', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Stock anterior')),
                ('stock_nuevo', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Stock nuevo')),
                ('observacion', models.TextField(blank=True, null=True, verbose_name='Observación')),
                ('fecha_movimiento', models.DateTimeField(auto_now_add=True, verbose_name='Fecha del movimiento')),
            ],
            options={
                'verbose_name': 'Movimiento de Stock',
                'verbose_name_plural': 'Movimientos de Stock',
                'ordering': ['-fecha_movimiento'],
            },
        ),
        migrations.RemoveField(
            model_name='stockproducto',
            name='fecha_ultimo_movimiento',
        ),
        migrations.AddField(
            model_name='stockproducto',
            name='fecha_ultimo_egreso',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Último egreso'),
        ),
        migrations.AddField(
            model_name='stockproducto',
            name='fecha_ultimo_ingreso',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Último ingreso'),
        ),
        migrations.AddIndex(
            model_name='producto',
            index=models.Index(fields=['codigo'], name='productos_p_codigo_bbe51f_idx'),
        ),
        migrations.AddIndex(
            model_name='producto',
            index=models.Index(fields=['nombre'], name='productos_p_nombre_456643_idx'),
        ),
        migrations.AddIndex(
            model_name='stockproducto',
            index=models.Index(fields=['producto', 'subalmacen'], name='productos_s_product_ae1742_idx'),
        ),
        migrations.AddField(
            model_name='movimientostock',
            name='creado_por',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_stock', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='movimientostock',
            name='ingreso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_stock', to='ingresos.ingreso'),
        ),
        migrations.AddField(
            model_name='movimientostock',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='productos.producto'),
        ),
        migrations.AddField(
            model_name='movimientostock',
            name='subalmacen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='almacenes.subalmacen'),
        ),
    ]
