# Generated by Django 6.0.3 on 2026-03-20 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_movimientostock_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimientostock',
            name='tipo',
            field=models.CharField(blank=True, choices=[('INGRESO', 'Ingreso'), ('EGRESO', 'Egreso'), ('AJUSTE', 'Ajuste')], max_length=10, null=True, verbose_name='Tipo'),
        ),
    ]
